[package]
name = "rustapp"
version = "0.1.0"
edition = "2021"
description = ""
license = ""

[lib]
crate-type = ["staticlib"]

[dependencies]
zephyr = " 3.7.0"
anyhow = { version = "1.0", default-features = false }
ohw-wallets = { path = "./wallets", default-features = false, features = [
  "crypto-psa",
] }
ohw-protocol = { path = "./protocol" }

[build-dependencies]
zephyr-build = "3.7.0"

[profile.release]
codegen-units = 1
strip = true
panic = 'abort'
opt-level = 'z'
lto = true
