[package]
name = "rustapp"
version = "0.1.0"
edition = "2021"
description = ""
license = ""

[lib]
crate-type = ["staticlib"]

[dependencies]
zephyr = "3.7.0"
bip32 = { version = "0.5.2", default-features = false, features = ["alloc", "secp256k1"] }
hex = { version = "0.4", default-features = false, features = ['alloc'] }
tiny-keccak = { version = "2.0", features = ["keccak"] }
