[package]
name = "rustapp"
version = "0.1.0"
edition = "2021"
description = ""
license = ""

[lib]
crate-type = ["staticlib"]

# If use cortex-m0 and other target not support atomic, use this patch
[patch.crates-io]
bytes = { git = "https://github.com/atlas-aero/rt-bytes", branch = "cfg_target_has_atomic_v1.6.0" }

[dependencies]
zephyr = " 3.7.0"
anyhow = { version = "1.0", default-features = false }
ohw-wallets = { path = "./wallets", default-features = false, features = [
  "crypto-psa",
] }
ohw-protocol = { path = "./protocol" }

[build-dependencies]
zephyr-build = "3.7.0"

[profile.release]
codegen-units = 1
strip = true
panic = 'abort'
opt-level = 'z'
lto = true
