[package]
name = "rustapp"
version = "0.1.0"
edition = "2021"
description = ""
license = ""

[lib]
crate-type = ["staticlib"]

[dependencies]
zephyr = "3.7.0"
bip39 = { git = "https://github.com/vincent-forks/rust-bip39.git", default-features = false, features = [
  'alloc',
] }
