[package]
name = "ohw-protocol"
version = "0.0.1"
edition = "2021"
description = ""
license = ""

[dependencies]
anyhow = { version = "1.0", default-features = false }
prost = { version = "0.13", default-features = false, features = ["prost-derive"] }

[build-dependencies]
prost-build = "0.13"
